<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9uXdL2X\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9uXdL2X/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9uXdL2X.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9uXdL2X\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9uXdL2X\App_KernelDevDebugContainer([
    'container.build_hash' => '9uXdL2X',
    'container.build_id' => 'eafe5823',
    'container.build_time' => 1684832426,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9uXdL2X');
